
name: Android app build CI

on: 
  workflow_dispatch:
    inputs:
    
      flavor:
        description: 'Flavor(staging,alpha,production)'     
        required: true
#        default: 'Staging'
        
      artifacts:
        description: 'Artifacts(assemble,bubdle)'
        required: true
#        default: assemble

      build:
        description: 'Build(debug,release)'
        required: true
        

jobs:
  build_production:
    if: github.event.inputs.flavor == 'production' && github.event.inputs.artifacts == 'assemble' && github.event.inputs.build == 'debug'
    name: Build Production debug APK and upload in artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
